const users = [
  {
    id: 1,
    name: "Ali Sadeghi",
    city: "Tehran",
    job: "Programmer",
    age: 33,
    experience: "10 Years",
    level: "Senior",
    image: "user1.jfif",
  },
  {
    id: 2,
    name: "Sara Ahmadi",
    city: "Shiraz",
    job: "UI/UX Designer",
    age: 27,
    experience: "5 Years",
    level: "Mid-Level",
    image: "user2.jfif",
  },
  {
    id: 3,
    name: "Reza Mohammadi",
    city: "Isfahan",
    job: "Backend Developer",
    age: 31,
    experience: "8 Years",
    level: "Senior",
    image: "user3.jfif",
  },
  {
    id: 4,
    name: "Negin Karimi",
    city: "Tabriz",
    job: "Frontend Developer",
    age: 24,
    experience: "2 Years",
    level: "Junior",
    image: "user4.jpg",
  },
  {
    id: 5,
    name: "Amir Hosseini",
    city: "Mashhad",
    job: "DevOps Engineer",
    age: 35,
    experience: "11 Years",
    level: "Senior",
    image: "user5.jfif",
  },
  {
    id: 6,
    name: "Parisa Norouzi",
    city: "Rasht",
    job: "Mobile Developer",
    age: 29,
    experience: "6 Years",
    level: "Mid-Level",
    image: "user6.jfif",
  },
];

export default users;
